<a href="https://colab.research.google.com/github/AbhinavKumar07/P124/blob/main/Project_C124.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Print Elements of Array

**Problem**: Given 1X1 Array:

```
arr_1d = [53, 78, 90, 12, 15, 65, 44, 32, 29, 36]
```

1. Print 3rd and 9th element of the array.
2. Change  3rd and 9th element to 100.


In [29]:
# write code here
import numpy as np

arr_1d = np.array([523, 75, 330, 12, 143, 655, 4334, 3242, 689, 316])

print(arr_1d[2])
print(arr_1d[8])

arr_1d[2] = 100
arr_1d[8] = 100

print(arr_1d)

330
689
[ 523   75  100   12  143  655 4334 3242  100  316]


## Update Diagonal Elements of Multidimensional Array

**Problem**: Given a 3x3 array, change all the diagonal elements of the matrix to 0.

```

arr_2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]
```





In [30]:
#Write code here

arr_2d = np.array([[1,2,3],[7,8,9],[4,5,6]])

for i in range(3):
  for j in range(3):
    if i == j :
      arr_2d[i][j] = 0

print(arr_2d)



[[0 2 3]
 [7 0 9]
 [4 5 0]]


## Numbers of Rows & Column

**Problem**: Write a program to find the number of rows and columns present in the matrix given below.
Note: Initialize the matrix using NumPy.

```
 A= [[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]]
```



In [31]:
# write code here
A = np.array([[9,5,6,1,-2],[3,-8,1,2,0],[6,9,3,3,5]])

rows = len(A)
columns = len(A[0])

print(rows , " rows and " , columns , " columns")

3  rows and  5  columns


## Scalar Multiplication

**Problem**: Print each element of the following matrix. Initialize the matrix using NumPy.  <br />
Also, multiply the matrix with n = 150 and print the matrix after multiplication.
   
```
 B=[[-8,0,2,4],[5,2,-1,7]]
```


   

In [32]:
B = np.array([[-8,0,2,4],[5,2,-1,7]])

C = np.array([[0,0,0,0],[0,0,0,0]])
n = 150

for i in range(len(C)):
  for j in range(len(C[0])):
    C[i][j] += B[i][[j]] * 150

print(C)


[[-1200     0   300   600]
 [  750   300  -150  1050]]
